<?php
$rutaBD="Z:/redes.bas";
$rutaDT="/baseDatos/";
$archClientes="entradaDatos/clientes.csv";
$tablaClientes="tablas/tablaClientes.csv";
$tablaHospot="tablas/tablaHospot.csv";
$debugHospot="log/debugHospot.csv";
$tablaSaldos="pagos/tablaSaldos.csv";
$logtablaSaldos="log/logtablaSaldos.csv";
$archMora="salidaDatos/mora.csv";
$archMoraDescortar="entradaDatos/mora2.csv";
$archCortados="salidaDatos/cortados.csv";
$archDescortados="salidaDatos/desCortados.csv";
$archAvisoPago="salidaDatos/avisoPago.csv";
$logMora="log/logMora.csv";
$logCortados="log/logCortados.csv";
$logAvisoPago="log/logAvisoPago.csv";
$logDescortados="log/logDescortados.csv";
$pagosDelDia="pagos/HOY-SUM.csv";
?>