<?php
include_once($_SERVER['DOCUMENT_ROOT'].'/PATH/pathSistemaCobranza.php');
$rutaBD=UNIDAD."/redes.bas";
$rutaDT="/baseDatos/";
$salidaDatos="salidaDatos/";
$archClientes="entradaDatos/clientes";
$tablaClientes="tablas/tablaClientes";
$tablaHospot="tablas/tablaHospot.csv";
$debugHospot="log/debugHospot.csv";
$tablaSaldos="pagos/tablaSaldos.csv";
$logtablaSaldos="log/logtablaSaldos.csv";
$archMora="salidaDatos/mora.csv";
$archMoraDescortar="entradaDatos/mora2.csv";
$logMora="log/logMora.csv";
$logCortados="log/logCortados.csv";
$logAvisoPago="log/logAvisoPago.csv";
$logDescortados="log/logDescortados.csv";
$pagosDelDia="pagos/HOY-SUM.csv";
?>